# 项目
app:
  id: lyc.springboot.demo
  name: learning springboot
  version: 1.0.0

  # 指定环境
spring:
  profiles:
    active:
      - dev
apollo:
  # 就是apollo config server的地址
  meta: http://meta.apollo.xxx.cn
  bootstrap:
    # 是否开启 Apollo
    enabled: true
    eagerLoad:
      # 将 Apollo 加载提到初始化日志系统之前，如果设置为false，则配置中心中修改日志信息不会生效
      enabled: true
    namespaces: application, sensitive-config, message
  cacheDir: ./config
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 配置微服务的地址
microservice:
  url:
    # 订单微服务的地址
    orderUrl: http://localhost:8002
    # 用户微服务的地址
    userUrl: http://localhost:8001
    # 支付微服务的地址
    payUrl: http://localhost:8003
    # 购物车微服务的地址
    shoppingUrl: http://localhost:8004

# 配置文件上传大小限制
file:
  maxSize: 1024MB
# 配置文件上传路径
filePath: /home/lyc/upload/


# 日志配置
logging:
  level:
    com.example.lyc.springboot.demo: debug
    org.springframework: warn
    io.swagger: debug
    org.springdoc: debug

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

## MyBatis
#mybatis-plus:
#  # 搜索指定包别名
#  typeAliasesPackage: com.example.**.entity
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      update-fill: modify_by,modify_time
      page-size: 10
  mapper-locations: classpath*:mapper/**Mapper.xml
  # 只要多加这一句就能用mybatis-plus了
  configuration:
    map-underscore-to-camel-case: true

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

springdoc:
  api-docs:
    path: /swagger-docs
    enabled: true


# 阿里云
aliyun:
  oss:
    endpoint: <your-oss-endpoint>
    accessKeyId: <your-access-key-id>
    accessKeySecret: <your-access-key-secret>
    bucketName: <your-bucket-name>